### ISSUE TITLE
Support numeric range queries

### ISSUE THREAD

**Issue by arsaboo** [MoeMusic/Moe#199]
### Describe the new feature

It would be great if we can use numerical values in queries. For example, `year` greater than 2010 or `year` between 1990 and 2000. This does not have to be limited to `year`, but can be extended to other fields, e.g., `bitrate`, `rating`.

### Use case

This can be used to create smart playlists. For example, we can create a playlist for all tracks from '90s.

**Comment by jtpavlock** [comment]
Thanks for creating the feature request, this is something I'd definitely like to see implemented. 

Do you have any suggestions on the query syntax? I know beets uses '..', but having never really used these queries myself I wonder if you had any other ideas or if that seemed good.

**Comment by arsaboo** [comment]
I think the `..` syntax is fine (unless you have other thoughts). It is easy to understand and use and I am sure the target audience is familiar with that syntax.
