### ISSUE TITLE
Import crashes when creating album from Musicbrainz release with unknown format

### ISSUE THREAD

**Issue by ali-ramadhan** [MoeMusic/Moe#218]
### Describe the bug

When adding a few albums I encountered a `KeyError` when Moe tries to create an album from a Musicbrainz release. I think it's because the release format is unknown (for example: https://musicbrainz.org/release/8bd1c26c-68d5-4c27-b32d-cf3393bc1059).

The obvious fix would be to update the format on Musicbrainz (format should be CD I think), but Moe shouldn't be crashing either. Not sure what `media` should be set to in this case. Python doesn't have a `missing` data type so maybe `None` or the string `unknown`?

This would be a different issue but it's also worth noting that some releases come in a mix of media. For example, https://musicbrainz.org/release/827008e9-0779-4fd5-8e5a-7322462eba91 has a CD (Disc 1) and a DVD-Video (Disc 2), although for music tagging only the first disc matters.

### To Reproduce

```python
from moe.plugins.musicbrainz import get_album_by_id
get_album_by_id("8bd1c26c-68d5-4c27-b32d-cf3393bc1059")
```

Stacktrace:

```
KeyError                                  Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 get_album_by_id("8bd1c26c-68d5-4c27-b32d-cf3393bc1059")

File ~/build/Moe/moe/plugins/musicbrainz/mb_core.py:378, in get_album_by_id(release_id)
    374 release = musicbrainzngs.get_release_by_id(release_id, includes=RELEASE_INCLUDES)
    376 log.info(f"Fetched release from musicbrainz. [release={release_id!r}]")
--> 378 return _create_album(release["release"])

File ~/build/Moe/moe/plugins/musicbrainz/mb_core.py:425, in _create_album(release)
    413 else:
    414     label = None
    416 album = MetaAlbum(
    417     artist=_flatten_artist_credit(release["artist-credit"]),
    418     barcode=release.get("barcode"),
    419     catalog_nums=catalog_nums,
    420     country=release.get("country"),
    421     date=_parse_date(release["date"]),
    422     disc_total=int(release["medium-count"]),
    423     label=label,
    424     mb_album_id=release["id"],
--> 425     media=release["medium-list"][0]["format"],
    426     original_date=_parse_date(release["release-group"]["first-release-date"]),
    427     title=release["title"],
    428 )
    429 for medium in release["medium-list"]:
    430     for track in medium["track-list"]:

KeyError: 'format'
```

### Setup

- OS: Linux Debian 5.10
- Python version: 3.9.12
- Moe version: master branch

**Comment by jtpavlock** [comment]
Thanks for the report, you're right, we definitely should crash here, and can just set `media` to `None`.

As far as releases with multiple medias, it probably means `media` should be a multi-value field which should be a separate feature request.

**Comment by ali-ramadhan** [comment]
Awesome, thanks for the quick fix!
