### ISSUE TITLE
Bug in example code on documentation homepage?

### ISSUE THREAD

**Issue by jaimet** [MoeMusic/Moe#269]
### Describe the bug
When I run the code on the [documentation homepage](https://mrmoe.readthedocs.io/en/latest/index.html), it doesn't work.

### To Reproduce

Run the code on the [documentation homepage](https://mrmoe.readthedocs.io/en/latest/index.html). Observe that it doesn't work:

```
$ ./please-dear-lord-deliver-me-from-beets
Traceback (most recent call last):
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 13, in main
    config.Config(config_dir=Path.home() / ".config" / "my_script", init_db=False)
    ^^^^^^
NameError: name 'config' is not defined. Did you mean: 'Config'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 33, in <module>
    main()
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 14, in main
    except config.ConfigValidationError as err:
           ^^^^^^
NameError: name 'config' is not defined. Did you mean: 'Config'?

```
(I found the code snippet on the [api page](https://mrmoe.readthedocs.io/en/latest/developers/api/api.html), but I can't get that to run either. That's a different problem however.)

### Expected behavior

I don't know, but it must be different to what I'm seeing.

### Setup

- OS: debian bookworm
- Python version: 3.11.2
- Moe version: 2.1.1
- (moe-musicbrainz   1.0.0)

**Comment by jtpavlock** [comment]
Hi there, currently out of town so unable to properly test, but there does seem to be an error with the code! Does it work if you change the two instances of `config.Config` to just `Config`?

**Comment by jaimet** [comment]
If I change `config.Config` on line 13 to just `Config`, then I get:

```
$ ./please-dear-lord-deliver-me-from-beets 
Traceback (most recent call last):
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 13, in main
    Config(config_dir=Path.home() / ".config" / "my_script", init_db=False)
                      ^^^^
NameError: name 'Path' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 33, in <module>
    main()
  File "/home/wtf/argh/./please-dear-lord-deliver-me-from-beets", line 14, in main
    except config.ConfigValidationError as err:
           ^^^^^^
NameError: name 'config' is not defined. Did you mean: 'Config'?

```
If I then change `Path.home()` on line 13 to `pathlib.Path.home()`, and `config.ConfigValidationError` on line 14 to `ConfigValidationError` then the script parses without error. :pray: 

[Here's the "working" version](https://github.com/MoeMusic/Moe/files/14796122/please-dear-lord-deliver-me-from-beets.txt) (renamed to `.txt` to get round github's attachment restrictions). I'll try to fix the snippet on the [api page](https://mrmoe.readthedocs.io/en/latest/developers/api/api.html) next.

**Comment by jaimet** [comment]
After some reflection, the fix for the [api page](https://mrmoe.readthedocs.io/en/latest/developers/api/api.html) is obvious: just set it to the first 10 lines of the "working" version above. All fixed.
